# Generated by Django 4.2.4 on 2023-09-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('url', models.TextField()),
            ],
        ),
    ]
