# Generated by Django 4.2.4 on 2023-11-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='ip',
        ),
    ]
